# Override values for testnet
#
mobilecoind:
  image:
    tag: ""
  chainID: test
  threshold: 3
  listenURI: insecure-mobilecoind://0.0.0.0:3229/
  pollInterval: 1
  peers:
  - url: 'mc://node1.test.mobilecoin.com:443/'
    txSource: 'https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.test.mobilecoin.com/'
  - url: 'mc://node2.test.mobilecoin.com:443/'
    txSource: 'https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node2.test.mobilecoin.com/'
  - url: 'mc://node3.test.mobilecoin.com:443/'
    txSource: 'https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node3.test.mobilecoin.com/'
  - url: 'mc://node1.consensus.mob.staging.namda.net:443/'
    txSource: 'https://s3-eu-central-1.amazonaws.com/staging-namda-payments-ledger/node1.consensus.mob.staging.namda.net/'
  - url: 'mc://node2.consensus.mob.staging.namda.net:443/'
    txSource: 'https://s3-eu-central-1.amazonaws.com/staging-namda-payments-ledger/node2.consensus.mob.staging.namda.net/'

gnosisConfig:
  safes:
  - safe_addr: "0x3F0aF8e39bF63f6Ca65d62f684acDCD7b6079E7f"
    api_url: https://safe-transaction-sepolia.safe.global/
    token_decimals_max: 6
    tokens:
      - token_id: 1
        token_type: ERC20_TRANSFER
        eth_token_contract_addrs: ["0xfdC112c39d0fafA45ec8B2cA9e46DFAB43b41575"]
        name: seUSD
        symbol: Token
        decimals: 18
        logo_uri: ""
        aux_burn_contract_addr: "0xF6970481dd09494099b5A2559E05Fa1Db6D6660B"
        aux_burn_function_sig: [199, 111, 6, 53]

ingress:
  host: auditor.test.mobilecoin.com

frontend:
  network: test
