# Default values for reserve-auditor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mobilecoind:
  image:
    repository: mobilecoin/reserve-auditor
    # this is set at mainnet/testnet.values file
    tag: ""
  resources:
    requests:
      cpu: 100m
      memory: 65Mi
  peers: []

ledgerScanner:
  image:
    repository: mobilecoin/reserve-auditor
    tag: ""
  resources:
    requests:
      cpu: 100m
      memory: 65Mi

httpServer:
  image:
    repository: mobilecoin/reserve-auditor
    tag: ""
  resources:
    requests:
      cpu: 100m
      memory: 65Mi

frontend:
  image:
    repository: mobilecoin/reserve-auditor-frontend
    tag: ""
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 65Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  env: []
  podAnnotations: 
    fluentbit.io/include: 'true'
    fluentbit.io/exclude-jaeger-agent: 'true'

api:
  replicas: 1
  nodeSelector: {}
  affinity: {}
  tolerations: []
  podAnnotations: 
    fluentbit.io/include: 'true'
    fluentbit.io/exclude-jaeger-agent: 'true'

persistence:
  enabled: true
  pvcSpec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 128Gi
    storageClassName: fast
    volumeMode: Filesystem

gnosisConfig:
  safes:
  - safe_addr: "0x3F0aF8e39bF63f6Ca65d62f684acDCD7b6079E7f"
    api_url: https://safe-transaction-sepolia.safe.global/
    token_decimals_max: 6
    tokens:
    - token_id: 1
      token_type: ERC20_TRANSFER
      eth_token_contract_addrs: ["0xfdC112c39d0fafA45ec8B2cA9e46DFAB43b41575"]
      name: seUSD
      symbol: Token
      decimals: 18
      logo_uri: ""
      aux_burn_contract_addr: "0xF6970481dd09494099b5A2559E05Fa1Db6D6660B"
      aux_burn_function_sig: [199, 111, 6, 53]

imagePullSecrets:
- name: docker-credentials

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations: 
    haproxy.org/path-rewrite: /api/(.*) /\1
    cert-manager.io/cluster-issuer: letsencrypt-production-http

