# Default values for reserve-auditor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mobilecoind:
  image:
    repository: mobilecoin/mobilecoind
    # this is set at mainnet/testnet.values file
    tag: ""
  resources:
    requests:
      cpu: 100m
      memory: 65Mi
  peers: []

ledgerScanner:
  image:
    repository: mobilecoin/reserve-auditor
    tag: ""
  resources:
    requests:
      cpu: 100m
      memory: 65Mi

httpServer:
  image:
    repository: mobilecoin/reserve-auditor
    tag: ""
  resources:
    requests:
      cpu: 100m
      memory: 65Mi

frontend:
  image:
    repository: mobilecoin/reserve-auditor-frontend
    tag: ""
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 65Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  env: []
  podAnnotations: 
    fluentbit.io/include: 'true'
    fluentbit.io/exclude-jaeger-agent: 'true'

api:
  replicas: 1
  nodeSelector: {}
  affinity: {}
  tolerations: []
  podAnnotations: 
    fluentbit.io/include: 'true'
    fluentbit.io/exclude-jaeger-agent: 'true'

persistence:
  enabled: true
  pvcSpec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 128Gi
    storageClassName: fast
    volumeMode: Filesystem

gnosisConfig:
  safes:
  - safe_addr: "0x36c4A3e3838974bb94Da7fC836987A68C7c0D34D"
    api_url: https://safe-transaction.goerli.gnosis.io/
    token_decimals_max: 6
    tokens:
    - token_id: 1
      token_type: ERC20_TRANSFER
      eth_token_contract_addr: "0xeC76FbFD75481839e456C4cb2cd23cda813f19B1"
      name: gRSV
      symbol: Token
      decimals: 18
      logo_uri: ""
      aux_burn_contract_addr: "0x89d2c2C7853AD6015d50f39A615196e17f13Cf59"
      aux_burn_function_sig: [199, 111, 6, 53]

imagePullSecrets:
- name: docker-credentials

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations: 
    haproxy.org/path-rewrite: /api/(.*) /\1
    cert-manager.io/cluster-issuer: letsencrypt-production-http

