FROM node:19.5.0-buster-slim AS deps
WORKDIR /app
COPY frontend .

RUN yarn install --non-interactive

FROM node:19.5.0-buster-slim AS builder
WORKDIR /app
COPY frontend .
COPY --from=deps /app/node_modules ./node_modules

USER node

EXPOSE 3000

CMD ["yarn","start-mainnet-prod"]
