# This file needs to be linked, with MC_GNOSIS_SAFE_CONFIG env var being set to its path

[[safes]]
safe_addr = "0x39366D9a9aD99f9839b83e996b4c6851372F7017"  # Safe address that is available once it is created
api_url = "https://safe-transaction.goerli.gnosis.io/"
token_decimals_max = 9

[[safes.tokens]]
token_id = 0
token_type = "ERC20"
eth_token_contract_addr = "0x50b347Ddbc73e45BD54683a57fcc28AA449Cf229" # GoerliTestTether
name = "GoerliTestTether"
symbol = "GTT"
decimals = 18
logo_uri = "https://safe-transaction-assets.gnosis-safe.io/tokens/logos/0x50b347Ddbc73e45BD54683a57fcc28AA449Cf229.png"
aux_burn_contract_addr = "0xcc7a61bc0f74121871267d4ae6c4a2477d745d94" # Auxiliary metadata contract address
aux_burn_function_sig = [0xc7, 0x6f, 0x06, 0x35] # Auxiliary metadata emitBytes function signature hash

[[safes.tokens]]
token_id = 1
token_type = "ERC20"
eth_token_contract_addr = "0x5ADF1E64251b5010d5597003FD1Be2d6365F5e84" # TestMobTether
name = "TestMobTether"
symbol = "TMOBT"
decimals = 18
logo_uri = "https://safe-transaction-assets.gnosis-safe.io/tokens/logos/0x5ADF1E64251b5010d5597003FD1Be2d6365F5e84.png"
aux_burn_contract_addr = "0xcc7a61bc0f74121871267d4ae6c4a2477d745d94" # Auxiliary metadata contract address
aux_burn_function_sig = [0xc7, 0x6f, 0x06, 0x35] # Auxiliary metadata emitBytes function signature hash
