name: Lint
description: Check the git status of the current directory, and raise an error if there are uncommitted changes.

runs:
  using: composite
  steps:
    - name: Checking Lint
      shell: bash
      run: |
        cargo clippy --all --all-features --all-targets

        rustup toolchain install stable
        cargo +stable install cargo-sort

        for toml in $(grep --exclude-dir cargo --exclude-dir mobilecoin --exclude-dir rust-mbedtls --include=Cargo.toml -r . -e '\[workspace\]' | cut -d: -f1); do
          pushd $(dirname $toml) >/dev/null
          echo "Linting in $PWD"
          cargo sort --workspace --grouped --check
          cargo fmt -- --unstable-features --check
          cargo clippy --all --all-features
          echo "Linting in $PWD complete."
          popd >/dev/null
        done
