apiVersion: v1
kind: Service
metadata:
  name: {{ include "reserve-auditor.fullname" . }}-frontend
  labels:
    {{- include "reserve-auditor.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reserve-auditor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
