apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "reserve-auditor.fullname" . }}
  labels:
    {{- include "reserve-auditor.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: ""
  tls:
  - secretName: {{ include "reserve-auditor.fullname" . }}-ingress-tls
    hosts:
    - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "reserve-auditor.fullname" . }}-api
            port:
              name: http
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "reserve-auditor.fullname" . }}-frontend
            port:
              name: http
