apiVersion: v1
kind: Service
metadata:
  name: {{ include "reserve-auditor.fullname" . }}-frontend
  labels:
    {{- include "reserve-auditor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "reserve-auditor.fullname" . }}-api
  labels:
    {{- include "reserve-auditor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: server
