apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "reserve-auditor.fullname" . }}
  labels:
    {{- include "reserve-auditor.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "reserve-auditor.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "reserve-auditor.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "reserve-auditor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "reserve-auditor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: gnosis-config
          configMap:
            name: {{ include "reserve-auditor.gnosisConfigName" . }}
      {{- with .Values.persistence }}
        {{- if not .enabled }}     
        - name: {{ .Chart.Name }}
          emptyDir: {}
        {{- end}}
      {{- end}}
      containers:
        {{- with .Values.mobilecoind }}
        - name: mobilecoind
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: mobilecoind-rpc
              containerPort: 3229
          livenessProbe:
            exec:
              command:
                - "/usr/local/bin/grpc_health_probe"
                - "-addr=:3229"
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - "/usr/local/bin/grpc_health_probe"
                - "-addr=:3229"
            failureThreshold: 4
            periodSeconds: 30
          volumeMounts:
            - name: {{ $.Chart.Name }}
              mountPath: /ledger/
            - name: {{ $.Chart.Name }}
              mountPath: /mobilecoind/
          env:
            - name: "RUST_BACKTRACE"
              value: "full"
            - name: "RUST_LOG"
              value: "info,rustls=warn,hyper=warn,tokio_reactor=warn,mio=warn,want=warn,reqwest=warn,rusoto_core=error,rusoto_signature=error,h2=error"
          command:
            - /bin/bash
            - -ec
            - |
               /usr/bin/mobilecoind \
                 --chain-id {{ .chainID }} \
                 {{- range .peers }}
                 --peer {{ .url }} \
                 --tx-source-url {{ .txSource }} \
                 {{- end }}
                 --poll-interval {{ .pollInterval }} \
                 --quorum-set '{"threshold": {{ .threshold }}, "members": [
                   {{- range (initial .peers) -}}
                     {{ include "reserve-auditor.quorumItem" . }},
                   {{- end -}}
                   {{- include "reserve-auditor.quorumItem" (last .peers) }}]}' \
                 --ledger-db /ledger/ledger.db \
                 --mobilecoind-db /mobilecoind/mobilecoind.db \
                 --listen-uri {{ .listenURI }}
                 \
          resources:
            {{- toYaml .resources | nindent 12 }}
        {{- end }}
        {{- with .Values.ledgerScanner }}
        - name: ledger-scanner
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          command:
           - /bin/bash
           - -ec
           - |-
             until test -f /ledger/ledger.db/data.mdb; do
               sleep 3
               echo 'waiting for ledger db'
             done
             mkdir -p /data/auditor
             touch /data/auditor/auditor.db
             /usr/local/bin/mc-reserve-auditor \
               scan-ledger \
                 --ledger-db /ledger/ledger.db \
                 --reserve-auditor-db /auditor/auditor.db \
                 --gnosis-safe-config /config/gnosis/config.json
          volumeMounts:
            - name: gnosis-config
              mountPath: /config/gnosis
            - name: {{ $.Chart.Name }}
              mountPath: /ledger/
            - name: {{ $.Chart.Name }}
              mountPath: /auditor/
          resources:
            {{- toYaml .resources | nindent 12 }}
        {{- end }}
        {{- with .Values.httpServer }}
        - name: http-server
          command:
            - /bin/bash
            - -ec
            - |
              until test -f /auditor/auditor.db; do
                sleep 3
                echo 'waiting for auditor db'
              done
              /usr/local/bin/mc-reserve-auditor \
                start-http-server \
                --host 0.0.0.0 \
                --reserve-auditor-db /auditor/auditor.db \
                --gnosis-safe-config /config/gnosis/config.json
          volumeMounts:
            - name: gnosis-config
              mountPath: /config/gnosis
            - name: {{ $.Chart.Name }}
              mountPath: /auditor/
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 2
            periodSeconds: 15
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 2
            periodSeconds: 15
            initialDelaySeconds: 30
          resources:
            {{- toYaml .resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  {{- with .Values.persistence }}
    {{- if .enabled }}
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ $.Chart.Name }}
      spec:
        {{- toYaml .pvcSpec | nindent 8 }}
    {{- end }}
  {{- end }}
