apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reserve-auditor.fullname" . }}-mobilecoind
  labels:
    {{- include "reserve-auditor.labels" . | nindent 4 }}
data:
  mobilecoind.conf: |
    [program:mobilecoind]
    priority=100

    {{- with .Values.mobilecoind }}
    command=/usr/bin/mobilecoind
      --chain-id {{ .chainID }}
      {{- range .peers }}
      --peer {{ .url }}
      --tx-source-url {{ .txSource }}
      {{- end }}
      --poll-interval {{ .pollInterval }}
      --quorum-set '{"threshold": {{ .threshold }}, "members": [
        {{- range (initial .peers) -}}
          {{ include "reserve-auditor.quorumItem" . }},
        {{- end -}}
        {{- include "reserve-auditor.quorumItem" (last .peers) }}]}'
      --ledger-db /data/ledger/ledger.db
      --mobilecoind-db /data/mobilecoind/mobilecoind.db
      --listen-uri {{ .listenURI }}
    {{- end }}

    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    autorestart=true
