apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reserve-auditor.fullname" . }}-scanner
  labels:
    {{- include "reserve-auditor.labels" . | nindent 4 }}
data:
  ledger_scanner.conf: |
    [program:scanner]
    priority=100

    SGX_MODE=HW IAS_MODE=PROD CONSENSUS_ENCLAVE_CSS=$(pwd)/../mobilecoin/consensus-enclave.css \
    command=/usr/local/bin/mc-reserve-auditor scan-ledger 
    	--ledger-db /data/ledger/ledger.db 
    	--watcher-db /data/watcher/watcher-db
    	--reserve-auditor-db /data/auditor/auditor.db
    	--gnosis-safe-config /config/gnosis/config.json

    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stdout
    stderr_logfile_maxbytes=0
    autorestart=true
