name: Reserve Auditor CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  IAS_MODE: DEV
  SGX_MODE: SW

permissions:
  contents: read
  checks: write

jobs:
  test-rust-build:
    runs-on: mco-dev-large-x64
    container: mobilecoin/builder-install:v0.0.25
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0
    - name: Setup Rust
      uses: ./.github/actions/setup-rust
    - name: Cargo build
      shell: bash
      run: |
        cargo build --release --locked
    - name: Check dirty git
      uses: ./.github/actions/check-dirty-git

  lint-rust:
    runs-on: mco-dev-large-x64
    container: mobilecoin/builder-install:v0.0.25
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0
    - name: Setup Rust
      uses: ./.github/actions/setup-rust
      with:
        components: rustfmt, clippy
    - name: Run lint script
      uses: ./.github/actions/lint
    - name: Check dirty git
      uses: ./.github/actions/check-dirty-git
  test:
    runs-on: mco-dev-large-x64
    container: mobilecoin/builder-install:v0.0.25
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0
    - name: Setup Rust
      uses: ./.github/actions/setup-rust
    - name: Cargo test
      shell: bash
      run: |
        cargo test
    - name: Check dirty git
      uses: ./.github/actions/check-dirty-git
