---
name: shared-cd

env:
  DOCKERHUB_ORG: mobilecoin
  DOCKER_IMAGE: reserve-auditor
  CHART_REPO: https://harbor.mobilecoin.com/chartrepo/mobilecoinfoundation-public


on:
  push:
    branches:
      - adds-github-actions
      - release\/.*

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.docker_meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate Docker Tags
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKERHUB_ORG }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha

      - name: Setup Docker Buildx
        id: buildx
        if: "! contains(github.event.head_commit.message, '[skip docker]')"
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to DockerHub
        if: "! contains(github.event.head_commit.message, '[skip docker]')"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to DockerHub
        uses: docker/build-push-action@v3
        if: "! contains(github.event.head_commit.message, '[skip docker]')"
        with:
          context: .
          file: Dockerfile
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  setup-environment:
    runs-on: [self-hosted, Linux, small]
    needs: []
      # - docker
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Package and publish chart
      if: "! contains(github.event.head_commit.message, '[skip charts]')"
      uses: mobilecoinofficial/gha-k8s-toolbox@a89efdf4305f3b926b1bb61a59f267532406e653
      with:
        action: helm-publish
        chart_repo_username: ${{ secrets.HARBOR_USERNAME }}
        chart_repo_password: ${{ secrets.HARBOR_PASSWORD }}
        chart_repo: ${{ env.CHART_REPO }}
        chart_app_version: v0.0.0
        chart_version: v0.0.0
        chart_path: ./deploy/charts/reserve-auditor

    - name: Create namespace
      uses: mobilecoinofficial/gha-k8s-toolbox@v1
      with:
        action: namespace-create
        namespace: mainnet-reserve-auditor
        rancher_cluster: utility-r1-b-k8s
        rancher_url: ${{ secrets.RANCHER_URL }}
        rancher_token: ${{ secrets.RANCHER_TOKEN }}

