name: tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: mco-dev-small-x64
    steps:
    - name: bump tag
      uses: mobilecoinofficial/gh-actions/tag@v0
      with:
        github_token: ${{ secrets.ACTIONS_TOKEN }}
